# Generated by Django 4.2.17 on 2024-12-15 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='impact',
            field=models.TextField(default='Impact not specified'),
        ),
        migrations.AddField(
            model_name='threat',
            name='mitigation',
            field=models.TextField(default='Mitigation strategy not specified'),
        ),
        migrations.AlterField(
            model_name='option',
            name='threat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.threat'),
        ),
    ]
